-- ~/.config/nvim/lua/plugins/init.lua
-- All plugin specifications

return {
  require("plugins.ui"),
  require("plugins.treesitter"),
  require("plugins.lsp"),
  require("plugins.completion"),
  require("plugins.telescope"),
  require("plugins.editing"),
  require("plugins.formatting"),
  require("plugins.git"),
  require("plugins.whichkey"),
  require("plugins.trouble"),
  require("plugins.debug"),
  require("plugins.markdown"),
  require("plugins.project"),
  require("plugins.copilot"),
  require("plugins.test"),
  require("plugins.terminal"),
  require("plugins.ai"),
  require("plugins.visuals"),
  require("plugins.session"),
  require("plugins.navic"),
  require("plugins.tasks"),
  require("plugins.tools"),
  require("plugins.minimap"),
  require("plugins.screencast"),
  require("plugins.octo"),
  require("plugins.flash"),
  require("plugins.todo"),
  require("plugins.notify"),
  require("plugins.harpoon"),
}
